### ISSUE TITLE
Headers not sticking to top with React native 0.63.2

### ISSUE THREAD

**Issue by sagrawalcb** [JungHsuan/react-native-collapsible-tabview#10]
my react-native version is 0.63.2
 ```
"react-native-tab-view": "^2.14.4",
"react-native": "0.63.2",
```
I just copy-pasted the code from the Repo and the headers are not sticking to the top anymore
the screenshot is of Pixel_3a_XL_API_27
<img width="453" alt="Screenshot 2020-09-28 at 10 36 02 PM" src="https://user-images.githubusercontent.com/62282243/94464101-9e494680-01db-11eb-8b85-7d3638cf31d4.png">

**Comment by JungHsuan** [comment]
@sagrawalcb I just create a new project and have no problem running the example on Pixel 4 with
```
    "react-native": "0.63.2",
    "react-native-tab-view": "^2.15.1"
```
Since this is just an example code not a library, I think you should make some changes to fit your project.
