### ISSUE TITLE
How to keep navigation header on top?

### ISSUE THREAD

**Issue by ydhnwb** [JungHsuan/react-native-collapsible-tabview#24]
I have navigation header for showing back button and title. I just want to keep this on top and not get replaced by collapsed header or the tabs.

**Comment by ydhnwb** [comment]
I want the white header (back button and title) is keep on top, while the green will be scrollable.
I copied your code on ScrollableHeader and just add this
```
    <SafeAreaView style={styles.container}>
      <Header title="Detail Bahan Baku" />

      <View style={{flex: 1}}>
        {renderTabView()}
        {renderHeader()}
      </View>
    </SafeAreaView>
```

**Comment by JungHsuan** [comment]
Hi @ydhnwb, do you mean that you don't want the collapsed header or the tabs view scroll over on top of the ``<Header/>``?

**Comment by ydhnwb** [comment]
Yes. I want header to keep on top, and the tab will hanging below the header when it scrolled
![Screenshot_1647403019](https://user-images.githubusercontent.com/26734262/158514087-806496b3-7535-4204-8f14-5899a8986938.png)
![Screenshot_1647403024](https://user-images.githubusercontent.com/26734262/158514086-a0b7c041-9207-403b-991e-de3d89664441.png)

**Comment by JungHsuan** [comment]
Is this what you attempt to achieve?
![Simulator Screen Recording - iPhone 13 - 2022-03-16 at 12 35 55](https://user-images.githubusercontent.com/10951814/158517535-1bab262d-b50d-49f2-ae42-68b1a34c320c.gif)

**Comment by ydhnwb** [comment]
yes, exactly like that

**Comment by JungHsuan** [comment]
Here is my example code:
```
const Header = ({title}) => {
  return (
    <View
      style={{
        backgroundColor: 'white',
        height: 65,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
      }}>
      <Text style={{fontSize: 20}}>{title}</Text>
    </View>
  );
};

const App = () => {
  return (
    <SafeAreaView style={{flex: 1}}>
      <Header title="Detail Material" />
      <CollapsibleTabView />
    </SafeAreaView>
  );
};
```
For: `CollapsibleTabView`, I simply copy my `collapibleTabView.js` and modify the style like this:
```
  return (
    <View style={{flex: 1, overflow: 'hidden'}}>
      {renderTabView()}
      {renderHeader()}
    </View>
  );
```
By adding `overflow: 'hidden'` to prevent the header from `renderHeader()` scroll over on top of the navigation bar.

**Comment by ydhnwb** [comment]
Thank you very much. I'll try to implement that
