### ISSUE TITLE
SafeAreaView on iOS scrolls with the tabs

### ISSUE THREAD

**Issue by deshika94** [JungHsuan/react-native-collapsible-tabview#28]
I have no issue with this on android, it works perfectly. But on iOS, when I scroll up, the status bar becomes transparent and I can see the header and other components being scrolled behind the status bar. I did wrap everything inside a SafeAreaView with a background color, but when I scroll, the background color of the SafeAreaView also scrolls up. The weird thing is, when I add a navigation header, the tab contents scroll behind it so that works well. Any idea on how I can fix this?

**Comment by JungHsuan** [comment]
Hi @deshika94, would you like to share your code or screenshots?

**Comment by deshika94** [comment]
@JungHsuan Thank you for the quick response. For now, I was able to solve it by including overflow:'hidden' inside the view. Seems to be working fine on iOS now! :)
 Before ->
![simulator_screenshot_CEF170D9-44CB-4D4C-8A82-508747D60C2B](https://user-images.githubusercontent.com/78348822/158507792-16d3cbf3-6bc6-4804-851d-f353654cd84c.png)


Code ->

![Screen Shot 2022-03-16 at 11 56 31 AM](https://user-images.githubusercontent.com/78348822/158507830-cd1daff4-5b51-4ce6-b6d9-62a24272cd4f.png)
fff0-eba2-4f64-b46e-0adfa019f310.png)

**Comment by deshika94** [comment]
Result ->

![simulator_screenshot_90B2186C-DE4B-485A-B9C9-23D0392F9BA4](https://user-images.githubusercontent.com/78348822/158507942-e220c0d7-d9b8-4448-b8ee-52a5cd8c68a5.png)

**Comment by JungHsuan** [comment]
Oh! I see your point. That's because the header is set to ``absolute``.
Thanks for the great solution by using `overflow:'hidden'`
