### ISSUE TITLE
Crashing when calling  syncScrollOffset() function.

### ISSUE THREAD

**Issue by sagrawalcb** [JungHsuan/react-native-collapsible-tabview#3]
`item.value.scrollaToOffset is not function.`

**Comment by k9p5** [comment]
Just replace both lines with: `item.value.getNode().scrollToOffset({`

**Comment by JungHsuan** [comment]
Yes,  @kpaulus1997, thank you for your reply.
@sagrawalcb you should add `getNode()` on the ref of animated component before react-native 0.62.0.

 ```
listRefArr.current.push({
    key: route.key,
    value: ref.getNode(),
});  
```

**Comment by sagrawalcb** [comment]
This did the trick. Thanks
