### ISSUE TITLE
How to implement in class component

### ISSUE THREAD

**Issue by Lzadhito** [JungHsuan/react-native-collapsible-tabview#8]
Any tutorial how to implement it in class component? I'm already write lot of my codes with class component and its kinda hard to implement this while this code written in hooks

**Comment by JungHsuan** [comment]
Hi, you will need to do something like:
1.  ``useRef`` variable to ``this.xxx``
2. ``useState`` to normal state.
3. ``useEffect`` to ``componentDidMount`` and don't forget to remove the listener in ``componentWillUnmount``

**Comment by Lzadhito** [comment]
> Hi, you will need to do something like:
> 
> 1. `useRef` variable to `this.xxx`
> 2. `useState` to normal state.
> 3. `useEffect` to `componentDidMount` and don't forget to remove the listener in `componentWillUnmount`

thank you 👍
